safe:        true
auto:        true
server:      true
baseurl:     /

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /:year/:month/:day/:title

## Variables
title : The Setkeh Project 
description : Portfolio and Code Rants an Riots 
url : http://setkeh.com
tagline : Miniature-Nemesis
author :
  name : Setkeh
  email : setkeh@gmail.com
  github : setkeh
  twitter : setkeh
  feedburner : setkeh
  
production_url : https://github.com/setkeh/miniature-nemesis
